### ISSUE TITLE
Avoid blocklist division and pass whole blocklist at once to block service

### ISSUE THREAD

**Issue by dmstern** [dmstern/likers-blocker#88]
When collecting very large lists of likers, it can be very annoying to click on all these buttons, open the block service in several tabs and run into errors when you are not logged in.

![grafik](https://user-images.githubusercontent.com/5219707/167313898-5fb29b55-504a-4a55-95ca-9c2e6afab32d.png)

**ToDo:**

* [x] Store collected users in local storage
* [x] read them from local storage on the service side
* [x] divide API list in several API calls to avoid error response

**Comment by henzeb** [comment]
we shouldn't want to click links at all. a button block all and maybe at the end: "are you sure". you could let it post as json body. If then needed in parts, the user has no problems with that.

**Comment by dmstern** [comment]
@henzeb yes, this would be a good idea. The problem ist: I did not manage to do the authentication in the extension itself yet. So we decided to do the authentication via the ichbinhiertwittertools python backend and then pass the data from the extension over a GET request so we need no authentication in the extension frontend itself.
If you have an idea how to authenticate a user from the browser extension directly, let me know. :) We wouldn't even need the python backend, we could pass the data directly to the Twitter API (see #54).

**Comment by SysAdminDoc** [comment]
I've been trying to figure out how to make a userscript that will run on the ichbinhiertwittertools URL and all it does is looks for the ban button and clicks it. I can figure out a way to open all the links myself but a userscript that will automatically click the button would be awesome. Would minimize 70% of clicking.

**Comment by henzeb** [comment]
> @henzeb yes, this would be a good idea. The problem ist: I did not manage to do the authentication in the extension itself yet. So we decided to do the authentication via the ichbinhiertwittertools python backend and then pass the data from the extension over a GET request so we need no authentication in the extension frontend itself. If you have an idea how to authenticate a user from the browser extension directly, let me know. :) We wouldn't even need the python backend, we could pass the data directly to the Twitter API (see #54).

well, you don't have to do the authentication in the extension itself. When collecting usernames, you have plenty of time to check if the user is authenticated, if not, the user get's a button to authenticate first. when authenticated, the user should click 'block them all' and THEN you could post them yourself. Then the splitting problem is not much of a problem anymore.

so basically you have 2 endpoints. `authentication check` and `block`. and an authentication page.
